### ISSUE TITLE
Only keep newest episode

### ISSUE THREAD

**Issue by mfmangano** [XilinJia/Podcini#138]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/XilinJia/podcini/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/XilinJia/Podcini/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

7.1.1

### Where did you get the app from

F-Droid

### Problem you may be having, or feature you want

Would like a podcast-specific option to fetch latest episode and delete older episodes as well as mark them watched, so episodes on device are always the latest.

**Comment by XilinJia** [comment]
Thanks for the idea.  Can you outline a rough workflow? Like at what event the episodes should be deleted or marked watched, etc?

**Comment by mfmangano** [comment]
On episode refresh, the app would check each subscription for new episodes. If one is found, it would be fetched as usual. When this happens the app checks to see if that subscription has the 'keep only new episodes' switch on; if so, it would delete and mark watched any episode present in that subscription with an older publication date.

This would assure that not only would the app update in the background, but also when you open the app only the newest episodes would be present/downloaded, with all older episodes marked watched/deleted.


Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Dec 28, 2024, 3:40 AM by ***@***.***:

**Comment by XilinJia** [comment]
The workflow doesn't sound very practical.  Say if you have 10 episodes downloaded in the feed that you set "keep only new episodes", at the refresh (automatic or manual) when there are new episodes, why would you want to delete the ones you've downloaded (still unplayed)?

For your purpose, did you try to see if the filters would help you?

**Comment by mfmangano** [comment]
I use the app on my limited storage capacity phone. I would like to listen to the podcasts when away from WiFi, but I don't want to pay for data downloads, so it is best for me to have mobile data downloads off. I subscribe to some news podcasts that have hourly updates. I think that if a new episode comes out before I listen to the old episode, the old one wasn't a priority and I don't care if it gets replaced with the new. For those few subscriptions with episodes I don't ever want deleted, I'd have them update but not download; when I want to consume those I would download any episode manually, listen, then manually delete.

This would allow my phone to have limited storage taken up, and Podcini.R would always have the most up-to-date episodes downloaded and available off-line. I think many would be interested in this ability, as long as manual control is available for exceptions.
Thanks for the consideration and a great app!

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Dec 29, 2024, 9:56 AM by ***@***.***:

**Comment by mfmangano** [comment]
That sounds wonderful! It would make the app much more usable in my situation. Thank you for the quality programming!


Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Dec 30, 2024, 12:54 PM by ***@***.***:

**Comment by XilinJia** [comment]
check out 7.2.0 and let know your experiences

**Comment by mfmangano** [comment]
Sorry, I only see 7.1.1 (my current version) on fdroid. Is the source on github the new one? I guess could try to compile the github  source, but I'm not a programmer. Really looking forward to the new version.

BTW, thanks for the prompt fix.

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 2, 2025, 4:28 PM by ***@***.***:

**Comment by mfmangano** [comment]
Hehehe, just found 7.2 on github. I'll try it out and let you know. Thanks again.

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 2, 2025, 5:53 PM by ***@***.***:

**Comment by mfmangano** [comment]
OK, been, playing with 7.2.1, but I must be doing something wrong. Even with it set up, seems to be downloading everything without deleting/marking played the old episodes. Here's my settings:

- For a test, I subscribed to only 1 podcast (NPR News Now, news pod with hourly updated episodes.
- Under Settings>Downloads:
     - refresh: 1 hour
     - Automatic Download: On
     - Episode Cache: 4 (since it states this is the total number of episodes for all subscriptions on the device, and downloads will stop if this limit is reached; shouldn't be needed if "replace" option is used, I would think)
     - Episode Cleanup: When not in queue 
     - Download When Not Charging: On
     - Auto Delete: On
     - Auto Delete From Local Folders: On
     - Keep Important Episodes: On
     - Delete Removes from Queue: On

Subscription Settings:
     - Auto Add New to Queue: On
     - Auto Delete: Global Default
     - Include in Auto Downloads: On
     - Autodownload Policy:
          - Only New: On
               - Replace: On

Complicated, but I think all the switches are right to update hourly with the latest episode and delete/mark watched the old episodes. What it's doing it downloading all new episodes, but keeping old ones and keeping all in the queue. Any hints as to what I'm doing wrong?

Oh, and when I highlight an old episode in my Episode list and hit "Delete episode media" I get an error "Unable to delete file.: file:///storage/emulated/0/Android/data/ac.mdiq...", so I can't delete the old ones manually (other than going into a filemanager and deleting that directory).

Thanks, looking forward to getting this to work.




Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 2, 2025, 9:28 PM by ***@***.***:

**Comment by XilinJia** [comment]
> error "Unable to delete file.: file:///storage/emulated/0/Android/data/ac.mdiq..."

This is a problem introduced in 7.2.0 when fileUrl in Episode is changed to a uri string but the delete routine did not follow the new approach - fixed in 7.2.2.  this is the problem that prevented the older episodes from being deleted. 

Will check on the NPR podcast.

Thanks for the detailed report.

**Comment by XilinJia** [comment]
7.2.2 appears working. Let me know your experience.

**Comment by XilinJia** [comment]
No problems for this?

**Comment by mfmangano** [comment]
Sorry I didn't write back sooner; bewn busy with other things.
Still having problems with autodownload. Have it turned on, episode include in downloads on, episode cache set to zero to keep it on, policy set for replace. Initially seemed to work, but recently stopped downloading {I'm running 7.2.3). Thought it was my vpn being seen as a metered connection, but same results with vpn off on wifi connection. And when I tried to change metered connection settings to test this, xt would allow me to select checkboxes, but would not keep the selected options on page refresh.



Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 11, 2025, 6:33 AM by ***@***.***:

**Comment by XilinJia** [comment]
I see.

Just so that we can better understand about the problem, does autodownload with other policies (without Replace) work for you, with or without other settings like vpn or metered connection?  If so, then perhaps the Replace policy has some issues.  If other policies behave in the same way as with Replace in these conditions, then we will check about vpn or metered connection.

**Comment by mfmangano** [comment]
Just tried a manual refresh with only new episodes on and replace off. Immediately picked up the last 3 episodes as new (NPR News Now, hourly broadcast) but didn't download any. Will try again with VPN (mullvad) off in an hour, but I did try running previously with no VPN, with the same results. 

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 11, 2025, 9:37 AM by ***@***.***:

**Comment by mfmangano** [comment]
Turned VPN off, then on again. Waited an hour and did another manual refresh and it downloaded current episode (autodownload on, only new episodes with replace). Going to keep that episode and turn on hourly refresh. Let you know what happens. 

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 11, 2025, 10:22 AM by ***@***.***:

**Comment by mfmangano** [comment]
Running 8.1.0 X version now. Manual downloading seems to work, but auto downloading doesn't, nor does download episode cleanup.

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 4, 2025, 7:12 AM by ***@***.***:

**Comment by XilinJia** [comment]
It appears the refresh schedule is not well observed some reason.  I normally set it for 12 hours and it does work to get new updates and new auto-downloads, but when I set it for 1 hour in a debug app, it doesn't auto refresh on that schedule.  Will check.

**Comment by XilinJia** [comment]
It seems that after you start up the refresh with an interval, the change to allow refresh and auto-download on metered network does not reset the refresh task (this happened in my case), even restarting the app won't help.  The only way to make the change effective is to change the interval.  Every time the interval is changed, the refresh task is reset.

In the coming release (Podcini.X), setting metered network will take effect on refresh.

**Comment by XilinJia** [comment]
OK, 8.1.1 better handles the auto-refresh.  You still need to make some change in related settings to reset the previous refresh task.  Changing the interval is simpler.  Let me know how that works for you.

BTW, the Replace policy of auto-download doesn't require any setting in auto-delete as it simply replaces old episodes and no further deletion is needed.

**Comment by mfmangano** [comment]
Ok, here's a follow-up.
New install 8.2.1
Added only 1 subscription (NPR News Now, hourly updates).
Turned on refresh, 1 hour interval.
Turned on automatic download (60 episode cache, default Episode cleanup, Download when not charging on)
Auto delete on
Delete removes from queue on
Metered network settings all off
In podcast settings:
Auto add new to queue on
Auto delete episode Global default
Auto download policy:
- When Newest unplayed checked, downloads new episode each hour
- When Only new items checked, downloads new episode each hour
- When Only new items checked with Replace also checked, podcast updates with new episodes available for streaming each hour, but nothing is downloaded.

I'd really like the last option working, as I have limited space on the phone.

Hope this helps

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 20, 2025, 1:32 PM by ***@***.***:

**Comment by XilinJia** [comment]
> When Only new items checked with Replace also checked, podcast updates with new episodes available for streaming each hour, but nothing is downloaded.

If you only want the new episodes to be available for streaming, you only need: Turned on refresh, 1 hour interval. Other settings are not needed. Not even the "Only new items checked with Replace" auto-download policy (since you don't want to to be downloaded).  If you want to see a stream button rather than a download button for every episode, you need to set "Prefer streaming" in global setting.  Note, even if you have a download button, you can always long-press on it to get the option to stream.

If you don't want to use metered network, then you can "Metered network settings all off", otherwise, you need at least to allow refresh and streaming for metered network.

**Comment by mfmangano** [comment]
I'd like only new episodes, all downloaded, with replace old episodes; seems with these settings nothing is auto downloading (it all works if replace is off, but not on)

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 29, 2025, 11:44 AM by ***@***.***:

**Comment by XilinJia** [comment]
> I'd like only new episodes, all downloaded, with replace old episodes; seems with these settings nothing is auto downloading (it all works if replace is off, but not on)

Are you on metered network?  If so, then you need to allow refresh, auto-downloaded etc. for metered network.  Note the app considers you are on metered network if your wifi hotspot is metered.

**Comment by mfmangano** [comment]
Only on wifi; not sure if the wifi is considered metered. I'll try allowing all metered on, with cell data for the phone off, so this should only affect wifi. I'll let you know.

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 29, 2025, 11:59 AM by ***@***.***:

**Comment by XilinJia** [comment]
> - When Newest unplayed checked, downloads new episode each hour
> - When Only new items checked, downloads new episode each hour
> - When Only new items checked with Replace also checked, podcast updates with new episodes available for streaming each hour, but nothing is downloaded.

This is strange. I'm running the last option again on the NPR podcast and see what happens.

**Comment by XilinJia** [comment]
I probably reproduced your issue.  I left the phone on cell data.  at the first refresh, the download stuck, one episode shows a progress at the download button, but nothing happens, and it seems to be stuck there for ever, manual refresh doesn't do anything. Then I switched to wifi, refresh works and a new episode got downloaded.  Will check.

**Comment by XilinJia** [comment]
The issue is on metered network, when auto-download is selected, both refresh and episode download need to be selected. With that, auto-download with replace works for me.

 In 8.3.1, I ensured the inter-dependencies in the dialog.

**Comment by mfmangano** [comment]
On 8.3.0, I just tried turning on Metered Settings: Podcast refresh, Episode download and Auto download. I get downloads when the Podcast Auto download policy is set to Newest unplayed and Only new items, but no downloads once I switch on the Replace switch. Maybe something to do with file delete? I do have a custom media folder selected (my Music folder), but I do have Auto delete from local folders on. I'll try running it after resetting custom media folder to default. 

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 30, 2025, 12:02 PM by ***@***.***:

**Comment by mfmangano** [comment]
On 8.3.0, I just tried turning on Metered Settings: Podcast refresh, Episode download and Auto download. I get downloads when the Podcast Auto download policy is set to Newest unplayed and Only new items, but no downloads once I switch on the Replace switch. Maybe something to do with file delete? I do have a custom media folder selected (my Music folder), but I do have Auto delete from local folders on. I'll try running it after resetting custom media folder to default. 
Just tried with default folder, same results; I get downloads but these stop once replace switch is turned on. Sorry...
Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 30, 2025, 1:52 PM by ***@***.***:

**Comment by XilinJia** [comment]
It seems your failure with the Replace policy has to do with your global "Episode cache" being set to a very tight number in relation to the numbers in all feeds.  That's perhaps the only situation that could affect the Replace auto-download. I corrected that in 8.3.2, so let me know how it works with that.

**Comment by mfmangano** [comment]
Doesn't seem to do it; still no auto-downloads when replace switch is on (8.3.2, btw). I even set global episode cache to 0 (unlimited), but still no downloads. 
Also, for some reason, now when an episode is played, it is marked played but not removed from the queue (streamed episodes).

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 1, 2025, 6:01 AM by ***@***.***:

**Comment by XilinJia** [comment]
> Also, for some reason, now when an episode is played, it is marked played but not removed from the queue (streamed episodes).

Did you turn off Settings -> Playback -> Queues -> Mark played removes from queue ?

> Doesn't seem to do it; still no auto-downloads when replace switch is on (8.3.2, btw). I even set global episode cache to 0 (unlimited), but still no downloads.  

I can't think of what can be wrong, as it works on my device.  Perhaps you can try delete the NPR feed and re-subscribe and reset it.

**Comment by mfmangano** [comment]
Nope, "Marked played removes from queue" is switched on; not a screen refresh issue either; played items remain in queue after stopping and starting the app.

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 1, 2025, 1:28 PM by ***@***.***:

**Comment by XilinJia** [comment]
> Nope, "Marked played removes from queue" is switched on; not a screen refresh issue either; played items remain in queue after stopping and starting the app.

I just tested it in an app with default settings: manually added a couple episodes into an active queue, long-press on the download button of an episode and chose stream, after playing, the episode was removed from then queue.  And when checking the queue history, the episode is there.

**Comment by mfmangano** [comment]
Sorry, i must be doing something wrong. I'll play with it. Thanks for the help. 

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 1, 2025, 2:01 PM by ***@***.***:

**Comment by XilinJia** [comment]
> Sorry, i must be doing something wrong. I'll play with it. Thanks for the help.

If it's not a big trouble, it might be better to back up your DB, uninstall/reinstall the app and import the DB (not the preferences), and start from there.

**Comment by mfmangano** [comment]
Ill give it a try. Thanks

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 1, 2025, 2:16 PM by ***@***.***:

**Comment by mfmangano** [comment]
I repeated your setup, new install, only added npr news now. Kept default settings, added 4 episodes to queue, streamed one and it was marked played and removed from queue. Then i turned on auto-download globally and for the subscription, checked only new items and replace. Without altering anything else when i went back to the queue and played the next episode, it finished, marked it played, but did not remove it from the queue (this was streamed, not downloaded). I then manually downloaded an episode on the queue without changing any settings and played it. Same results, marked played but not removed from queue. Also, not deleted, even though delete after playing was on in global settings. So turning on replace with auto-download seems to be messing up queue episode removal.


Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 1, 2025, 2:01 PM by ***@***.***:

**Comment by XilinJia** [comment]
OK, not sure if this is mentioned somewhere or not, but it's a feature started at a very earlier stage of the app (probably from the forked app), when auto-download is enabled for the app, all those episodes in the queue (the active queue after multiple queues are realized) that have not been downloaded are added for auto-download.  This is regardless of download policies.  But the auto-download only happens at refresh time.  Not sure if this relates to what you experience.  I will check about that. You may try clearing the queues for clean testing.

**Comment by XilinJia** [comment]
in 8.4.0, I changed something in auto-download that might improve your experience.

Also, an option to includes queues for auto-download is added in Settings -> Auto downloads

**Comment by mfmangano** [comment]
Running 8.5.2, still having no luck with autodownloads with replace. Now I'm getting a new error message as well (see screenshot).



Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364

**Comment by XilinJia** [comment]
see screenshot?

I'm pretty baffled with autodownloads with replace not working.  Could you possibly test with a fresh install and not import anything, make few changes to default settings, subscribe to NPR, enable auto-download globally and for NPR, set global cache to 20, and set cache for NPR to 1, set refresh interval for 1 hour, enable auto-download for mobile?  These are what I can think of.

If refresh doesn't run as scheduled, make sure Podcini is allowed to run in the background in Android settings.  If refresh still doesn't run, then it's a different issue.  Try to do manual refresh and see if auto-download works.

Let me know what happens.  This works for me.

**Comment by mfmangano** [comment]
I'll give it a try.
The screenshot was an error message stating:

SubscriptionsScreen:
StandaloneCorroutine was cancelled

(I've attached it to this email as well).

I'll let you know how the test goes.

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 6, 2025, 4:23 PM by ***@***.***:

**Comment by XilinJia** [comment]
> StandaloneCorroutine was cancelled

that does no harm. I started toasting lots of coding messages. At least they serve as some kind of notifications. I know some are meaningful and some are not quite.  As I mentioned in the release notes:

* error toasts can be toggled in Settings -> User interface -> Show error toasts (default to true)
* toast messages (error or not) are cached for the session and can be shown in Logs screen
	* this is true even "Show error toasts" is turned off

**Comment by mfmangano** [comment]
Just set up a new install as you stated. Tried a manual refresh so I wouldn't have to wait and got this error message:
Auto download not performed. Network true power: false.

Any ideas? I am using a VPN (Mullvad), but I have Podcini.X in the no vpn split tunneling setting they have. I also turned off the VPN fully as a trial, but got the same network power error. When I manually try to download an individual via download button rather than by refreshing, the download happens without error, even with vpn on.



Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 6, 2025, 11:23 AM by ***@***.***:

**Comment by XilinJia** [comment]
> power: false

There is a setting in global auto download screen: "Download when not charging".  You need to turn that on.

**Comment by mfmangano** [comment]
Ok, got it (8.5.4) all set up; seems to be working only partially tho, can't figure out why.

Have all 57 of my podcasts subscribed, all with include in auto downloads on,  only new items and replace turned on, aii with episode cache set to zero. In global settings  in downloads refresh set to 1 hour, no start set, under automatic download episode cache set to zero, episode cleanup to never, download when not charging on, include queue items to all queues.

A few of my podcasts (including the hourly NPR News Now) are downloading with replacement, the others have all new episodes listed as played; from the download log it seems they are downloading, and immediately are deleted and marked played, even though there are no other episodes in those subscriptions present.

Any ideas? Partially working at least at this point.

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 6, 2025, 3:49 PM by ***@***.***:

**Comment by XilinJia** [comment]
> Have all 57 of my podcasts subscribed, all with include in auto downloads on,  only new items and replace turned on, aii with episode cache set to zero. In global settings  in downloads refresh set to 1 hour, no start set, under automatic download episode cache set to zero, episode cleanup to never, download when not charging on, include queue items to all queues. A few of my podcasts (including the hourly NPR News Now) are downloading with replacement, the others have all new episodes listed as played; from the download log it seems they are downloading, and immediately are deleted and marked played, even though there are no other episodes in those subscriptions present.

I appreciate your testing with all possible conditions.

A couple things to clarify:

1. when setting "only new items" (with or without replace), new episode will be downloaded when the set cache is not full. The differences between "with or without replace" occurs when the cache is full: "without replace" will not download new items, but "with replace" will delete an older downloaded and download the new one.
2. setting feed episode cache zero currently actually set the cache to 0 (not unlimited as it's described, it's a bug and is fixed in the coming release). So I suspect that causes the "deleted and marked played" issue.

**Comment by mfmangano** [comment]
Ok, running the latest (8.5.5).
Sincn thn updatn it seems auto download isnt working at all. In global settings I have Downloads>Refresh Podcasts⋮1, Automatic Download:on, GlobaEpisode cache:75, Episode Cleanup:When Not Favorited, Download when not charging:on, Iclude queue item:all selected. Auto delete:on, Delete removes from queue:on, Metered network settings: all on.

In podcast individual settings Auto delete episode: global default, Include in auto downloads:on, Auto downliad policy: only new items plus replace, and Episode cache:1.

Any ideas? It refreshes every hour, but never downloads.
Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 14, 2025, 3:28 AM by ***@***.***:

**Comment by XilinJia** [comment]
in 8.5.5, auto-download shouldn't be non-functioning. I suspect other factors in your settings could affect that.

Most likely could be that you already have episodes downloaded (and probably marked played) in the feed, so they count into the cache you set.  There is a setting "Counting played" in feed settings which is defaulted to true.  You can try delete any previously downloaded episodes or set "Counting played" to false.

Also, as you included all queues for auto-download, if there are undownloaded episodes in queues at auto-download, they are included and count into you global cache.

**Comment by mfmangano** [comment]
Just installed 8.6.1. Fresh install, kept all defaults except turned on Automatic download, global episode cache: 25, Episode Cleanup When not favorited, Download when not charging on, Auto delete on, Keep important episodes on, delete removes from queue on, Metered network settings auto download, episode download, podcast refresh all on. Then added NPR News Now (hourly updated podcast), with Podcast settings Keep updated on, Auto Download on, Episode Cache 1, counting played on, Automation policy set to Only new items with Replace on.

I've been running for 12 hours now, seems it is downloading new episodes when refreshed, but it isn't deleting any downloads.
Any ideas? I'd like to use it, but I don't want my phone filling up with downloaded files.
Many thanks.

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 16, 2025, 3:55 AM by ***@***.***:

**Comment by XilinJia** [comment]
> I've been running for 12 hours now, seems it is downloading new episodes when refreshed, but it isn't deleting any downloads.

You mean when it's downloading new episode (with Replace) it's not deleting(replacing) the downloaded episode even though you set Episode Cache to 1?  The Replace policy doesn't depend on Episode Cleanup or Auto delete, since it doesn't add any number of downloaded.  So everytime, an old downloaded episode is kept while a new one is downloaded?  That sounds strange.  Let me test here and see what happens.

**Comment by XilinJia** [comment]
Found the newly introduced issue.  Actually, not only it doesn't delete old episode, it doesn't download the new.  Fixed in the coming release.

**Comment by mfmangano** [comment]
Well, I deleted all downloaded files and ran it; next episode downloaded properly, and the one after that downloaded and properly deleted the prior episode, so all working properly now; I'll run it overnight and let you know how it goes. I dont understand it, I made no setting changes. As long as it works 😁

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 17, 2025, 2:45 PM by ***@***.***:

**Comment by mfmangano** [comment]
Updated to 8.8.2
Have autodownload on with new episodes only with replace on. Some setting is messing up replace function; all new episodes are downloading properly, but replace doesn't seem to be replacing anything. Any ideas re: what could be blocking replace?

Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Feb 17, 2025, 4:02 PM by ***@***.***:

**Comment by XilinJia** [comment]
> Updated to 8.8.2 Have autodownload on with new episodes only with replace on. Some setting is messing up replace function; all new episodes are downloading properly, but replace doesn't seem to be replacing anything. Any ideas re: what could be blocking replace?

There have been some changes in the last couple releases. I see one a bit improper for the Replace policy (though it's not likely to affect delete). I amended it in 8.9.1, and also added more toast messages.  Do you know to check on Session messages in Logs screen?  If you notice something not working properly, check to see some strange messages there and let me know.

**Comment by mfmangano** [comment]
Since the upgrade I've been getting crashing www with refresh attempts.

```
type: crash
osVersion: google/akita/akita:16/BP4A.251205.006.E1/2025122501:user/release-keys
userType: full.secondary
flags: dev options enabled
package: ac.mdiq.podcini.X:236, targetSdk 36
process: ac.mdiq.podcini.X
processUptime: 2623 + 287 ms
installer: dev.imranr.obtainium

java.lang.IllegalArgumentException: Unmanaged objects must be part of the Realm, before they can be queried this way. Use `MutableRealm.copyToRealm()` to turn it into a managed object.
at io.github.xilinjia.krdb.internal.InternalMutableRealm.findLatest(InternalMutableRealm.kt:45)
at io.github.xilinjia.krdb.internal.SuspendableWriter$WriterRealm.findLatest(SuspendableWriter.kt:58)
at ac.mdiq.podcini.storage.database.EpisodesKt.setPlayState$lambda$0(Episodes.kt:342)
at ac.mdiq.podcini.storage.database.EpisodesKt.$r8$lambda$asFVpEhhHvxlhrcgb10TEd_Q5lE(Episodes.kt:0)
at ac.mdiq.podcini.storage.database.EpisodesKt$$ExternalSyntheticLambda5.invoke(R8$$SyntheticClass:0)
at io.github.xilinjia.krdb.internal.SuspendableWriter$write$2.invokeSuspend(SuspendableWriter.kt:125)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
at java.lang.Thread.run(Thread.java:1563)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: ***@***.***, Dispatchers.IO]
```



Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364

**Comment by XilinJia** [comment]
Thanks for reporting. should be fixed in 10.4.3. let me know how it works for you.
if it works, could you close this issue? for future issues, feel free to open on Podcini.X

**Comment by mfmangano** [comment]
Still getting crashes on refresh, now on 10.4.3

```
type: crash
osVersion: google/akita/akita:16/BP4A.251205.006.E1/2025122501:user/release-keys
userType: full.secondary
flags: dev options enabled
package: ac.mdiq.podcini.X:237, targetSdk 36
process: ac.mdiq.podcini.X
processUptime: 6223 + 487 ms
installer: dev.imranr.obtainium

java.lang.IndexOutOfBoundsException: [RLM_ERR_INDEX_OUT_OF_BOUNDS]: Requested index 18446744073709551615 calling get_any() on Results when max is 0
at io.github.xilinjia.krdb.internal.interop.CoreErrorConverter.asThrowable(CoreErrorConverter.kt:40)
at io.github.xilinjia.krdb.internal.interop.realmcJNI.realm_results_get(Native Method)
at io.github.xilinjia.krdb.internal.interop.realmc.realm_results_get(realmc.java:1040)
at io.github.xilinjia.krdb.internal.interop.RealmInterop.realm_results_get-qQKz07g(RealmInterop.kt:1953)
at io.github.xilinjia.krdb.internal.RealmResultsImpl.get(RealmResultsImpl.kt:71)
at io.github.xilinjia.krdb.internal.RealmResultsImpl.get(RealmResultsImpl.kt:50)
at ac.mdiq.podcini.storage.database.QueuesKt.calcPosition(Queues.kt:387)
at ac.mdiq.podcini.storage.database.QueuesKt.addToQueue$lambda$0(Queues.kt:157)
at ac.mdiq.podcini.storage.database.QueuesKt.$r8$lambda$J2fgavQtUW7R4KfA6hLbgjXPK9Q(Queues.kt:0)
at ac.mdiq.podcini.storage.database.QueuesKt$$ExternalSyntheticLambda7.invoke(R8$$SyntheticClass:0)
at io.github.xilinjia.krdb.internal.SuspendableWriter$write$2.invokeSuspend(SuspendableWriter.kt:125)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
at java.lang.Thread.run(Thread.java:1563)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: ***@***.***, Dispatchers.IO]
```



Words to live by:  



Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  



There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  



Sit Vis Nobiscum - Obi Wan  



Quando Omni Flunkus Moritati. - Red Green  



War is easier than daughters - Lord Stark 


Before was was was was was is - Anonymous

"As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson


You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who



If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy


There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov





Mark F. Mangano


718 Weadley Road


Radnor, PA 19087


***@***.*** ***@***.***>


H: 484-254-4056


M: 484-995-7364






Jan 9, 2026, 3:39 PM by ***@***.***:

> Since the upgrade I've been getting crashing www with refresh attempts.
>
> ```
> type: crash
> osVersion: google/akita/akita:16/BP4A.251205.006.E1/2025122501:user/release-keys
> userType: full.secondary
> flags: dev options enabled
> package: ac.mdiq.podcini.X:236, targetSdk 36
> process: ac.mdiq.podcini.X
> processUptime: 2623 + 287 ms
> installer: dev.imranr.obtainium
>
> java.lang.IllegalArgumentException: Unmanaged objects must be part of the Realm, before they can be queried this way. Use `MutableRealm.copyToRealm()` to turn it into a managed object.
> at io.github.xilinjia.krdb.internal.InternalMutableRealm.findLatest(InternalMutableRealm.kt:45)
> at io.github.xilinjia.krdb.internal.SuspendableWriter$WriterRealm.findLatest(SuspendableWriter.kt:58)
> at ac.mdiq.podcini.storage.database.EpisodesKt.setPlayState$lambda$0(Episodes.kt:342)
> at ac.mdiq.podcini.storage.database.EpisodesKt.$r8$lambda$asFVpEhhHvxlhrcgb10TEd_Q5lE(Episodes.kt:0)
> at ac.mdiq.podcini.storage.database.EpisodesKt$$ExternalSyntheticLambda5.invoke(R8$$SyntheticClass:0)
> at io.github.xilinjia.krdb.internal.SuspendableWriter$write$2.invokeSuspend(SuspendableWriter.kt:125)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
> at java.lang.Thread.run(Thread.java:1563)
> Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: ***@***.***, Dispatchers.IO]
> ```
>
>
>
> Words to live by:  
>
>
>
> Non impediti ratione cogitationis. Unencumbered by the thought process - Tom & Ray Magliozzi. Car Talk  
>
>
>
> There are 10 types of people in the world. Those who understand binary and those who don't. Anon.  
>
>
>
> Sit Vis Nobiscum - Obi Wan  
>
>
>
> Quando Omni Flunkus Moritati. - Red Green  
>
>
>
> War is easier than daughters - Lord Stark 
>
>
> Before was was was was was is - Anonymous
>
> "As I fear not a child with a weapon he cannot lift, I will never fear the mind of a man who does not think"   - The Way of Kings, Brandon Sanderson
>
>
> You know, the very powerful and the very stupid have one thing in common, they don't alter their views to fit the facts, they alter the facts to fit their views -  Doctor Who
>
>
>
> If we cannot now end our differences, at least we can help make the world safe for diversity - John F. Kennedy
>
>
> There is a cult of ignorance in the United States, and there always has been. The strain of anti-intellectualism has been a constant thread winding its way through our political and cultural life, nurtured by the false notion that democracy means that "my ignorance is just as good as your knowledge". - Isaac Asimov
>
>
>
>
>
> Mark F. Mangano
>
>
> 718 Weadley Road
>
>
> Radnor, PA 19087
>
>
> ***@***.*** ***@***.***>
>
>
> H: 484-254-4056
>
>
> M: 484-995-7364
>
>
>
>

**Comment by XilinJia** [comment]
OK, I see. 

so you set to add new items in queue after currently played? when the currently played is not in the queue or doesn't exist, this bug happens. fixed in the coming release: if no currently played, the new item is added to the front of the queue.
